apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
status:
  loadBalancer:
    ingress:
      - ip: 10.10.1.212
spec:
  tls:
    - hosts:
        - example.com
      secretName: new-tls-secret
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-grpc-greeter-server
                port:
                  number: 80
